const shopItemData = [
  {
    id: 1,
    name: "Lemonade cathel",
    price: "3 400",
    category: "chair",
    img: require("../../assets/ShopPage/furniture/cathel.png"),
    stars:require('../../assets/ShopPage/5star.png'),
    cName: "single-shop-item",
  },
  {
    id: 2,
    name: "Lui Peng",
    price: "15 000",
    category: "chair",
    img: require("../../assets/ShopPage/furniture/LuiPeng.png"),
    stars:require('../../assets/ShopPage/3star.png'),
    cName: "single-shop-item",
  },
  {
    id: 3,
    name: "P. Goldberg",
    price: "30 000",
    category: "chair",
    img: require("../../assets/ShopPage/furniture/Pgoldberg.png"),
    stars:require('../../assets/ShopPage/5star.png'),
    cName: "single-shop-item",
  },
  {
    id: 4,
    name: "Wally & sons",
    price: "17 000",
    category: "chair",
    img: require("../../assets/ShopPage/furniture/wally.png"),
    stars:require('../../assets/ShopPage/5star.png'),
    cName: "single-shop-item",
  },
  {
    id: 5,
    name: "Agata",
    price: "2 800",
    category: "table",
    img: require("../../assets/ShopPage/furniture/agata.png"),
    stars:require('../../assets/ShopPage/3star.png'),
    cName: "single-shop-item",
  },
  {
    id: 6,
    name: "Hannah",
    price: "5 000",
    category: "table",
    img: require("../../assets/ShopPage/furniture/hannah.png"),
    stars:require('../../assets/ShopPage/3star.png'),
    cName: "single-shop-item",
  },
  {
    id: 7,
    name: "sharma",
    price: "10 000",
    category: "light",
    img: require("../../assets/ShopPage/furniture/sharma.png"),
    stars:require('../../assets/ShopPage/3star.png'),
    cName: "single-shop-item",
  },
];

export default shopItemData;
